### ISSUE TITLE
Exception while invoking method 'SimpleChat.join' TypeError: SimpleChat.options.onJoin is not a function

### ISSUE THREAD

**Issue by haru08** [cesarve77/simple-chat#10]
Hi,

Would like to report an issue if the package is included `arillo:flow-router-helpers` it throws an error:

```
I20171114-12:29:37.766(8)? Exception while invoking method 'SimpleChat.join' TypeError: SimpleChat.options.onJoin is not a function
I20171114-12:29:37.767(8)?     at DDPCommon.MethodInvocation.SimpleChat.join (packages/cesarve:simple-chat/methods_server.js:67:28)
I20171114-12:29:37.768(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171114-12:29:37.768(8)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20171114-12:29:37.769(8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1134:15)
I20171114-12:29:37.769(8)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20171114-12:29:37.770(8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1134:15)
I20171114-12:29:37.770(8)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20171114-12:29:37.771(8)?     at new Promise (<anonymous>)
I20171114-12:29:37.771(8)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20171114-12:29:37.772(8)?     at packages/ddp-server/livedata_server.js:559:43
I20171114-12:29:44.888(8)? { message: 'sdfdsf',
```

Kindly check if I missed something.

Btw here are the installed packages:

```
kadira:flow-router
kadira:blaze-layout
erasaur:meteor-lodash
stolinski:stylus-multi
fortawesome:fontawesome
spiderable
fastclick
raix:handlebar-helpers
aldeed:autoform
accounts-ui@1.2.0
accounts-password@1.5.0
matb33:bootstrap-glyphicons
zimme:active-route
gwendall:auth-client-callbacks
aldeed:collection2-core
meteortoys:allthings
datariot:ganalytics
check@1.2.5
patrickml:swal
twbs:bootstrap
tsega:bootstrap3-datetimepicker
socialize:user-model 
socialize:messaging
socialize:base-model
aldeed:simple-schema
random
cesarve:simple-chat
arillo:flow-router-helpers
```

Thanks.

**Comment by openp2pdesign** [comment]
Same for me:

```
I20180303-00:12:49.606(1)? Exception while invoking method 'SimpleChat.join' TypeError: SimpleChat.options.onJoin is not a function
I20180303-00:12:49.606(1)?     at MethodInvocation.SimpleChat.join (packages/cesarve:simple-chat/methods_server.js:68:28)
I20180303-00:12:49.607(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180303-00:12:49.607(1)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180303-00:12:49.608(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180303-00:12:49.608(1)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180303-00:12:49.608(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180303-00:12:49.608(1)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180303-00:12:49.608(1)?     at new Promise (<anonymous>)
I20180303-00:12:49.630(1)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180303-00:12:49.630(1)?     at packages/ddp-server/livedata_server.js:559:43

```


and I don't have the `arillo:flow-router-helpers` package, but these ones

```
accounts-password                1.5.0* Password support for accounts
accounts-ui                      1.3.0  Simple templates to add login widgets to an app
alanning:roles                   1.2.16  Authorization package for Meteor
aldeed:collection2-core          2.1.2  Core package for aldeed:collection2
aldeed:delete-button             2.0.0  Provides a delete button UI component
aldeed:schema-index              2.1.2* Control some MongoDB indexing with schema options
aldeed:tabular                   2.1.1  Datatables for large or small datasets in Meteor
aldeed:template-extension        4.1.0  Adds template features currently missing from the templating package
allow-deny                       1.1.0  Implements functionality for allow/deny and client-side db operations
benmgreene:moment-range          2.10.6  Fancy date ranges for Moment.js packaged for Meteor.
blaze-html-templates             1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
cesarve:simple-chat             0.4.2+ Simple chat window. The star point to make your own chat
check                            1.3.0  Check whether a value matches a pattern
dburles:collection-helpers       1.1.0  Transform your collections with helpers that you define
dynamic-import                   0.3.0  Runtime support for Meteor 1.5 dynamic import(...) syntax
ecmascript                       0.10.4* Compiler plugin that supports ES2015+ in all .js files
es5-shim                         4.7.3  Shims and polyfills to improve ECMAScript 5 support
fourseven:scss                   4.5.4  Style with attitude. Sass and SCSS support for Meteor.js.
iron:router                      1.1.2  Routing specifically designed for Meteor
jparker:gravatar                 0.5.1  Simple package to use gravatar images
meteor-base                      1.3.0  Packages that every Meteor app needs
meteorhacks:unblock              1.1.0  a way to use this.unblock inside publications
meteortoys:toggle                4.0.0  An on-screen toggle to open Meteor Toys
mizzao:autocomplete              0.5.1  Client/server autocompletion designed for Meteor's collections and reactivity
mobile-experience                1.0.5  Packages for a great mobile user experience
momentjs:moment                  2.20.1* Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                            1.4.4* Adaptor for using MongoDB and Minimongo over DDP
msavin:mongol                    4.0.1  In-App MongoDB Editor.. now with improved third party package compatibility.
natestrauser:font-awesome        4.6.3  Latest version Font-Awesome loaded via CDN
natestrauser:select2             4.0.3  Select2 is a jQuery based replacement for select boxes.
npm-bcrypt                       0.9.3  Wrapper around the bcrypt npm package
peppelg:bootstrap-3-modal        1.0.4  Simple usage of bootstrap 3 modals.
reactive-var                     1.0.11  Reactive variable
reywood:publish-composite        1.5.2  Publish a set of related documents from multiple collections with a reactive join
session                          1.1.7  Session variable
shell-server                     0.3.1  Server-side component of the `meteor shell` command.
standard-minifier-css            1.4.1  Standard css minifier used with Meteor apps by default.
standard-minifier-js             2.3.2  Standard javascript minifiers used with Meteor apps by default.
tap:i18n                         1.8.2  A comprehensive internationalization solution for Meteor
tap:i18n-ui                      0.8.0  User interface for the tap-i18n package
tracker                          1.1.3  Dependency tracker to allow reactive callbacks
tsega:bootstrap3-datetimepicker  4.17.37_1  Bootstrap 3 DateTime picker from @Eonasdan, packaged for Meteor.js
twbs:bootstrap                   3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
useraccounts:bootstrap           1.14.2  Accounts Templates styled for Twitter Bootstrap.
useraccounts:iron-routing        1.14.2  UserAccounts package providing routes configuration capability via iron:router.
```

**Comment by openp2pdesign** [comment]
I found the problem: you need to declare the function in your options, in `export const SimpleChat = {`

```javascript
onJoin: function (roomId, username, name,date) {
            //server
        },
onLeft: function (roomId, username, name,date) {
            //server
        },
```
Or this can be solved easily in the package by adding them in config.js, I'm gonna send a pull request now
